name: example
version: 1.0.0
private: true

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.1.11
  font_awesome_pro_flutter:
    path: ..
