name: font_awesome_pro_flutter
description: |
  Simple, opinionated, codegen library for GraphQL. It allows you to
  generate serializers and client helpers to easily call and parse your data.

version: 0.0.2
homepage: https://github.com/heftapp/font_awesome_pro_flutter
repository: https://github.com/heftapp/font_awesome_pro_flutter
licence: MIT

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  build: ^2.0.1
  dart_style: ^2.0.1
  code_builder: ^4.0.0
  recase: ^4.0.0
  built_collection: ^5.1.1
  path: ^1.0.0
  glob: ^2.1.0
  analyzer: ^4.1.0

dev_dependencies:
  test: ^1.17.4
  build_test: ^2.1.0
  build_runner: ^2.0.3
