
name: Check PR
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  verify_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional PRs
        uses: Namchee/conventional-pr@v0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          issue: false
          verified_commits: true
          close: false

  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: 
          - beta
          - stable
          - dev
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
      - name: Bootstrap melos
        run: dart analyze --fatal-infos .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: 
          - beta
          - stable
          - dev

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
      - name: Bootstrap melos
        run: dart test

